#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Copyright (c) 2019, Justine Kizhakkinedath
# All rights reserved
#
# -----------------------------------------------------------------------------

/usr/local/bin/emacs --daemon
